spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.transaction: DEBUG
    org.testcontainers: INFO
    com.example: DEBUG

testcontainers:
  reuse:
    enable: true